version: '3.8'

services:
  auth:
    build: ./auth-service
    container_name: auth_service
    restart: always
    environment:
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=main_db
      - DB_USER=devuser
      - DB_PASS=devpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=django-insecure-a-random-key-change-this-later
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/app

  postgres:
    image: postgres:13
    container_name: auth_postgres
    restart: always
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: auth_redis
    restart: always

volumes:
  postgres_data: